begin;
create extension if not exists pgtap with schema extensions;
select plan(26);
select has_extension('postgis','PostGIS is enabled');
select has_table('public','accounts','accounts exists');
select has_table('public','bookings','bookings exists');
select has_table('public','ai_analysis_attempts','AI provider attempts are auditable');
select has_column('public','worker_profiles','service_origin','worker origin uses geography');
select has_column('public','addresses','location','address uses geography');
select has_column('public','service_requests','service_location','request snapshots geography');
select has_column('public','location_updates','location','tracking uses geography');
select has_index('public','worker_profiles','worker_profiles_service_origin_gix','worker geography has GiST index');
select has_index('public','service_requests','service_requests_location_gix','request geography has GiST index');
select has_function('public','transition_booking',array['uuid','booking_status','integer','text'],'booking transition RPC exists');
select has_function('public','confirm_cash_payment',array['uuid','text'],'cash confirmation RPC exists');
select has_function('public','set_worker_service_area',array['numeric','numeric','integer'],'worker service-area RPC exists');
select has_function('public','set_address_location',array['uuid','numeric','numeric'],'address location RPC exists');
select has_function('public','get_booking_tracking',array['uuid','integer'],'authorized tracking RPC exists');
select has_function('public','persist_ai_analysis',array['uuid','text','text','text','text','text','text','text','jsonb','jsonb'],'atomic AI persistence RPC exists');
select ok((select relrowsecurity from pg_class where oid='public.accounts'::regclass),'accounts RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.payments'::regclass),'payments RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.ai_analysis_attempts'::regclass),'AI attempts RLS enabled');
select is((select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and not c.relrowsecurity),0::bigint,'every public application table enables RLS');
select is((select count(*)::integer from storage.buckets where public=false),6,'all six application buckets are private');
select is(has_table_privilege('authenticated','public.bookings','insert'),false,'authenticated clients cannot insert bookings directly');
select is((select count(*) from information_schema.routine_privileges where specific_schema='public' and grantee in ('anon','PUBLIC') and privilege_type='EXECUTE' and routine_name in ('transition_booking','confirm_cash_payment','review_worker_verification','read_job_batch')),0::bigint,'anonymous roles cannot execute sensitive RPCs');
select has_trigger('auth','users','provision_account_after_auth_insert','Auth users provision immutable application accounts');
select has_trigger('auth','users','activate_account_after_email_confirmation','email confirmation activates pending accounts');
select throws_ok($$select public.permanently_delete(gen_random_uuid())$$,'42501','PERMANENT_DELETION_BLOCKED','permanent deletion fails closed');
select * from finish();
rollback;
